name: PSP Plugin Build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: pspdev/pspdev:latest

    steps:
      - uses: actions/checkout@v3

      - name: Compile PRX
        run: make

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: NightShift-Plugin
          path: nightshift.prx
